pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "abdelrahmannayf/jenkins-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        DEPLOYMENT_FILE = 'CI-CD/lap 25/deployment.yaml'
    }

    tools {
        maven "Maven"
    }

    stages {

        stage('Run Unit Test') {
            steps {
                dir('CI-CD/lap 25') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build App') {
            steps {
                dir('CI-CD/lap 25') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CI-CD/lap 25') {
                    sh "docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                    echo \$PASS | docker login -u \$USER --password-stdin
                    docker push ${DOCKER_IMAGE}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Delete Local Image') {
            steps {
                sh "docker rmi ${DOCKER_IMAGE}:${IMAGE_TAG}"
            }
        }

        stage('Update Deployment YAML') {
            steps {
                sh "sed -i 's|image:.*|image: ${DOCKER_IMAGE}:${IMAGE_TAG}|' '${DEPLOYMENT_FILE}'"
            }
        }

        stage('Commit & Push Changes to GitHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-cred', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                    sh """
                    git config user.email "jenkins@example.com"
                    git config user.name "Jenkins"

                    git add ${DEPLOYMENT_FILE}
                    git commit -m "Update image to ${IMAGE_TAG}" || echo "No changes to commit"

                    git push https://\$GIT_USER:\$GIT_PASS@github.com/abdelrahmannayf/ivolve-test.git HEAD:main
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline Finished."
        }
        success {
            echo "GitOps Update Completed 🚀"
        }
        failure {
            echo "Pipeline Failed ❌"
        }
    }
}
