@Library('shared-lib') _

pipeline {
    agent { label 'agent-1' }

    environment {
        DOCKER_IMAGE = "abdelrahmannayf/jenkins-app"
        TAG = "${BUILD_NUMBER}"
        NAMESPACE = "dev"
    }

    stages {

        stage('RunUnitTest') {
            steps {
                dir('CI-CD/lap23') {
                    runUnitTest()
                }
            }
        }

        stage('BuildApp') {
            steps {
                dir('CI-CD/lap23') {
                    buildApp()
                }
            }
        }

        stage('BuildImage') {
            steps {
                dir('CI-CD/lap23') {
                    buildImage(DOCKER_IMAGE, TAG)
                }
            }
        }

        stage('ScanImage') {
            steps {
                dir('CI-CD/lap23') {
                    scanImage(DOCKER_IMAGE, TAG)
                }
            }
        }

        stage('PushImage') {
            steps {
                dir('CI-CD/lap23') {
                    pushImage(DOCKER_IMAGE, TAG)
                }
            }
        }

        stage('RemoveImageLocally') {
            steps {
                dir('CI-CD/lap23') {
                    sh "docker rmi ${DOCKER_IMAGE}:${TAG}"
                }
            }
        }

        stage('DeployOnK8s') {
            steps {
                dir('CI-CD/lap23') {
                    deployOnK8s(DOCKER_IMAGE, TAG, NAMESPACE)
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline Finished'
        }
        success {
            echo 'Deployment Successful'
        }
        failure {
            echo 'Pipeline Failed'
        }
    }
}
