
pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "yourdockerhubusername/jenkins-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        DEPLOYMENT_FILE = "CI-CD/lap 22/deployment.yaml"
    }

    tools {
        maven "Maven"
    }

    stages {
        stage('Run Unit Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build App') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push ${DOCKER_IMAGE}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Delete Local Image') {
            steps {
                sh "docker rmi ${DOCKER_IMAGE}:${IMAGE_TAG}"
            }
        }

        stage('Update Deployment YAML') {
            steps {
                sh """
                sed -i 's|image:.*|image: ${DOCKER_IMAGE}:${IMAGE_TAG}|' ${DEPLOYMENT_FILE}
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh "kubectl apply -f ${DEPLOYMENT_FILE}"
            }
        }
    }

    post {
        always {
            echo "Pipeline Finished."
        }
        success {
            echo "Deployment Succeeded 🚀"
        }
        failure {
            echo "Deployment Failed ❌"
        }
    }
}
